int32 target_cable_id

float32 target_z_velocity
float32 target_yaw_rate

float32 duration_s # The duration for which the maneuver controller will keep publishing references before becoming idle.
bool sustain_action # If true, the maneuver controller will sustain the action running for the duration of the maneuver. Otherwise, it will succeed immediately but keep providing references for the duration.
---
---
