uint8 GRIPPER_COMMAND_OPEN = 0
uint8 GRIPPER_COMMAND_CLOSE = 1

uint8 gripper_command

---

uint8 GRIPPER_COMMAND_RESPONSE_SUCCESS = 0
uint8 GRIPPER_COMMAND_RESPONSE_INVALID_COMMAND = 1
uint8 GRIPPER_COMMAND_RESPONSE_ERROR = 2
uint8 GRIPPER_COMMAND_RESPONSE_TIMEOUT = 3

uint8 gripper_command_response